version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
  - source: groupproject1/django.service
    destination: /etc/systemd/system/
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
